### ISSUE TITLE
problem while compiling fasthenry2

### ISSUE THREAD

**Issue by rsmarinho** [ediloren/FastHenry2#3]
Hi,

When I try to compile the master branch the following error is thrown:

make[2]: Leaving directory '/home/rsmarinho/fasthenry/FastHenry2/src/fasthenry/sparse'
cc -o fasthenry -O -DFOUR -m64 induct.o gmres.o savemat_mod.o readGeom.o joelself.o writefastcap.o SetupMulti.o calcp.o SetupComputePsi.o mulSetup.o BreakupSeg.o Precond.o addgroundplane.o findpaths.o fillM.o cx_ludecomp.o parse_command_line.o default_opts.o Prec_cost.o hole.o dist_betw_fils.o mutual.o newPrecond.o deg_mutual.o barnoldi.o regurgitate.o mulGlobal.o mulDo.o mulMulti.o mulLocal.o mulMats.o direct.o uglieralloc.o capsolve.o  find_nonuni_path.o read_tree.o contact.o sparse/sparse.a -lm
/usr/bin/ld: gmres.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: readGeom.o:(.bss+0x20): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: joelself.o:(.bss+0x60): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: writefastcap.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: SetupMulti.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: calcp.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: SetupComputePsi.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: mulSetup.o:(.bss+0x2000): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: BreakupSeg.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: Precond.o:(.bss+0x0): multiple definition of `fp'; induct.o:(.bss+0x1e8): first defined here
/usr/bin/ld: Precond.o:(.bss+0x20): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: addgroundplane.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: findpaths.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: fillM.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: cx_ludecomp.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: parse_command_line.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: default_opts.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: Prec_cost.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: hole.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: dist_betw_fils.o:(.bss+0x20): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: mutual.o:(.bss+0x20): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: newPrecond.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: deg_mutual.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: barnoldi.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: regurgitate.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: mulGlobal.o:(.bss+0x400): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: mulDo.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: mulMulti.o:(.bss+0x60): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: mulLocal.o:(.bss+0x20): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: mulMats.o:(.bss+0x60): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: direct.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: capsolve.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: find_nonuni_path.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: read_tree.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
/usr/bin/ld: contact.o:(.bss+0x0): multiple definition of `timestuff'; induct.o:(.bss+0x200): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:26: fasthenry] Error 1
make[1]: Leaving directory '/home/rsmarinho/fasthenry/FastHenry2/src/fasthenry'
make: *** [Makefile:17: fasthenry] Error 2

I'm running Fedora 33 with gcc:
$ gcc --version
gcc (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)

Maybe a definition problem I do not know how to solve.

Thanks,
Rafael

**Comment by pasiz** [comment]
Same problem on ubuntu too:

gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0

**Comment by tenko** [comment]
You need the `-fcommon` flag for newer GCC versions due to missing header guards.
This works on Windows 10 and MSYS with GCC 11.2.0.

**Comment by aghaeifar** [comment]
To solve this, I opened /src/fasthenry/resusage.h and changed 
`struct rusage timestuff;`
to 
`inline struct rusage timestuff;`

and 
`struct tms timestuff;`
to
`inline struct tms timestuff;`

**Comment by irecana** [comment]
Hello, I am having the same issue on ubuntu 22.04, gcc 11.4.0
I tried adding 'inline', but it is still not working. Does anyone have a suggestion?

**Comment by tskaar** [comment]
I patched the following:

``` diff
diff --git a/src/fasthenry/Makefile b/src/fasthenry/Makefile
index ff6f2a9..9ebc0e3 100644
--- a/src/fasthenry/Makefile
+++ b/src/fasthenry/Makefile
@@ -1,4 +1,4 @@
-CFLAGS = -O -DFOUR -m64
+CFLAGS = -O -DFOUR -m64 -Wno-return-mismatch -Wno-implicit-int -Wno-implicit-function-declaration
 
 SHELL = /bin/sh
 RM = /bin/rm
diff --git a/src/fasthenry/Precond.c b/src/fasthenry/Precond.c
index d44cfce..d899cb6 100644
--- a/src/fasthenry/Precond.c
+++ b/src/fasthenry/Precond.c
@@ -31,7 +31,7 @@ is the default.  Most of this code is if'd out for this precond */
  ((nbr)->k == (nk)) && \
  ((nbr)->l == (nl)) )
 
-FILE *fp;
+extern FILE *fp;
 static char outfname[80];
 
 indPrecond(sys, indsys, w)
diff --git a/src/fasthenry/mulGlobal.c b/src/fasthenry/mulGlobal.c
index 1ea68cf..3f0d8ea 100644
--- a/src/fasthenry/mulGlobal.c
+++ b/src/fasthenry/mulGlobal.c
@@ -91,4 +91,13 @@ double axes[10][2][3];		/* the 2d image of the coordinate axes */
 int up_axis;			/* X,Y or Z => which axis is vertical in pic */
 char *line_file;		/* pointer to .fig superimposed line file */
 char *ps_file_base;		/* pointer to base name for .ps files */
+
+/* Resusage */
+#ifdef FOUR
+struct rusage timestuff;
+#endif
+
+#ifdef FIVE
+struct tms timestuff;
+#endif
 #endif
diff --git a/src/fasthenry/resusage.h b/src/fasthenry/resusage.h
index a16f15b..9172149 100644
--- a/src/fasthenry/resusage.h
+++ b/src/fasthenry/resusage.h
@@ -6,7 +6,7 @@
 #define NOTOTHER 1
 #include <sys/time.h>
 #include <sys/resource.h>
-struct rusage timestuff;
+extern struct rusage timestuff;
 #endif
 
 #ifdef FIVE
@@ -14,7 +14,7 @@ struct rusage timestuff;
 #include <sys/types.h>
 #include <sys/param.h>
 #include <sys/times.h>
-struct tms timestuff;
+extern struct tms timestuff;
 #endif
 
 /* define macros for time and resident memory usage checks */
diff --git a/src/fasthenry/sparse/Makefile b/src/fasthenry/sparse/Makefile
index a090c4c..1e31983 100644
--- a/src/fasthenry/sparse/Makefile
+++ b/src/fasthenry/sparse/Makefile
@@ -3,7 +3,7 @@
 #  Ken Kundert
 #  UC Berkeley
 #
-CFLAGS = -O -m64
+CFLAGS = -O -m64 -Wno-return-mismatch -Wno-implicit-int -Wno-implicit-function-declaration
 LINTFLAGS = -lc -lm
 SHELL = /bin/sh
 CC = cc
diff --git a/src/misc/Makefile b/src/misc/Makefile
index af6d21a..4a78101 100644
--- a/src/misc/Makefile
+++ b/src/misc/Makefile
@@ -1,4 +1,4 @@
-CFLAGS = -O -DFOUR -m64
+CFLAGS = -O -DFOUR -m64 -Wno-return-mismatch -Wno-implicit-int -Wno-implicit-function-declaration
 
 SHELL = /bin/sh
 RM = /bin/rm
diff --git a/src/zbuf/Makefile b/src/zbuf/Makefile
index 0dd5dd8..ead4450 100644
--- a/src/zbuf/Makefile
+++ b/src/zbuf/Makefile
@@ -43,7 +43,7 @@ LIBS = -lm
 #  - also used to select the correct CC macro definition for AIX machines
 #
 # for x86 64bit generic machine use (timers not supported)
-CFLAGS = -O -DOTHER -m64
+CFLAGS = -O -DOTHER -m64 -Wno-return-mismatch -Wno-implicit-int -Wno-implicit-function-declaration
 # for most machines running 4.2/3 use (only necessary if timers are needed)
 #CFLAGS = -O -DFOUR
 # for most machines running System V use (only necessary if timers are needed)
```

1. Add `-Wno-return-mismatch -Wno-implicit-int -Wno-implicit-function-declaration` to all Makefiles to make this closer to `--std=c90` without having to fix all the "modern" comments
2.  `resusage.h` gets imported multiple times through importing `mulGlobal.h`, hence set `timestuff` to extern in `resusage` and define it in `mulGlobal.c` instead.
3. `*fp` is defined multiple places (`Recond.c` and `induct.c`), hence define it as extern in `Recond.c` as well

Compiled sucessfully on ArchLinux using GCC v.14.2.1 and running some of the examples
